import type { LucideIcon } from "lucide-react";
import {
  // Buttons family (kept — same names, now centralized here)
  ArrowRight,
  Trash2,
  Download,
  Plus,
  Settings,
  ChevronDown,
  Mail,
  Bell,
  Check,
  Bold,
  Italic,
  Underline,
  AlignLeft,
  AlignCenter,
  AlignRight,
  PlayCircle,
  // Broader set for the Icons gallery / Badge / status indicators
  Home,
  Search,
  User,
  Users,
  Heart,
  Star,
  Info,
  CircleAlert,
  CircleCheck,
  CircleX,
  CircleHelp,
  TriangleAlert,
  Calendar,
  Clock,
  MapPin,
  Phone,
  Camera,
  Image,
  File,
  Folder,
  Link,
  Lock,
  LockOpen,
  Eye,
  EyeOff,
  Copy,
  Pencil,
  Filter,
  Grid2X2,
  List,
  Menu,
  MoreHorizontal,
  MoreVertical,
  RefreshCw,
  Save,
  Share2,
  ShoppingCart,
  Tag,
  Upload,
  Zap,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  X,
  Minus,
  Loader2,
  CircleUser,
  CircleDot,
  PanelLeft,
} from "lucide-react";

// The canonical icon-name registry for the whole library. Icons are
// referenced by name (not component) so the value can survive an HTML
// attribute boundary — same string works whether a component is used as
// plain React or wrapped as a Web Component (see src/elements).
export const ICONS: Record<string, LucideIcon> = {
  plus: Plus,
  download: Download,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "trash-2": Trash2,
  settings: Settings,
  mail: Mail,
  bell: Bell,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-left": ChevronLeft,
  "panel-left": PanelLeft,
  "chevron-right": ChevronRight,
  check: Check,
  "align-left": AlignLeft,
  "align-center": AlignCenter,
  "align-right": AlignRight,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  "play-circle": PlayCircle,
  home: Home,
  search: Search,
  user: User,
  users: Users,
  heart: Heart,
  star: Star,
  info: Info,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  "circle-help": CircleHelp,
  "circle-user": CircleUser,
  "circle-dot": CircleDot,
  "triangle-alert": TriangleAlert,
  calendar: Calendar,
  clock: Clock,
  "map-pin": MapPin,
  phone: Phone,
  camera: Camera,
  image: Image,
  file: File,
  folder: Folder,
  link: Link,
  lock: Lock,
  "lock-open": LockOpen,
  eye: Eye,
  "eye-off": EyeOff,
  copy: Copy,
  pencil: Pencil,
  filter: Filter,
  "grid-2x2": Grid2X2,
  list: List,
  menu: Menu,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "refresh-cw": RefreshCw,
  save: Save,
  "share-2": Share2,
  "shopping-cart": ShoppingCart,
  tag: Tag,
  upload: Upload,
  zap: Zap,
  x: X,
  minus: Minus,
  "loader-2": Loader2,
};

export const ICON_NAMES = Object.keys(ICONS).sort();

export function getIcon(name?: string | null): LucideIcon | undefined {
  if (!name) return undefined;
  return ICONS[name];
}
